### ISSUE TITLE
Error loading plugin. Could not locate the bindings file

### ISSUE THREAD

**Issue by ErikMHummel** [lprhodes/homebridge-apple-tv#27]
Hello,

I'm running my homebridge in a docker container on a RaspberryPi3. When I start the homebridge service, I see this in the logs:

>homebridge_1  | [2018-4-27 18:28:34] ====================
>homebridge_1  | [2018-4-27 18:28:34] ERROR LOADING PLUGIN homebridge-apple-tv:
>homebridge_1  | [2018-4-27 18:28:34] Error: Could not locate the bindings file. Tried:
>homebridge_1  |  → /homebridge/node_modules/ed25519/build/ed25519.node
>homebridge_1  |  → /homebridge/node_modules/ed25519/build/Debug/ed25519.node
>homebridge_1  |  → /homebridge/node_modules/ed25519/build/Release/ed25519.node
>homebridge_1  |  → /homebridge/node_modules/ed25519/out/Debug/ed25519.node
>homebridge_1  |  → /homebridge/node_modules/ed25519/Debug/ed25519.node
>homebridge_1  |  → /homebridge/node_modules/ed25519/out/Release/ed25519.node
>homebridge_1  |  → /homebridge/node_modules/ed25519/Release/ed25519.node
>homebridge_1  |  → /homebridge/node_modules/ed25519/build/default/ed25519.node
>homebridge_1  |  → /homebridge/node_modules/ed25519/compiled/8.11.1/linux/arm/ed25519.node
>homebridge_1  |     at bindings (/homebridge/node_modules/bindings/bindings.js:88:9)
>homebridge_1  |     at Object.<anonymous> (/homebridge/node_modules/ed25519/index.js:1:99)
>homebridge_1  |     at Module._compile (module.js:652:30)
>homebridge_1  |     at Object.Module._extensions..js (module.js:663:10)
>homebridge_1  |     at Module.load (module.js:565:32)
>homebridge_1  |     at tryModuleLoad (module.js:505:12)
>homebridge_1  |     at Function.Module._load (module.js:497:3)
>homebridge_1  |     at Module.require (module.js:596:17)
>homebridge_1  |     at require (internal/module.js:11:18)
>homebridge_1  |     at Object.<anonymous> (/homebridge/node_modules/node->appletv/dist/lib/pairing.js:5:17)
>homebridge_1  | [2018-4-27 18:28:34] ====================

I tried the steps in this post (different issue, but similar) with no luck. Any ideas?
https://github.com/nfarina/homebridge/issues/962

**Comment by MrDrache333** [comment]
Try reinstalling it...for manuall pairing you can install `node-appletv` with npm use `--unsafe-perm` as Parameter

**Comment by ErikMHummel** [comment]
All good after reinstall.
