### ISSUE TITLE
Updates?

### ISSUE THREAD

**Issue by Alexandre-Mainardi** [lprhodes/homebridge-apple-tv#3]
Hi, did you have any progress with this plugin? If not, im going to start a simple ON/OFF Homebridge Plugin. 

Thanks!

**Comment by deanlyoung** [comment]
I have a simple command to turn the Apple TV on, if you want to start there:
`curl 'http://XX.X.X.XX:3689/login?pairing-guid=Your-GUID-goes-here'`

**Comment by fboulegue** [comment]
Oh thats a nice one :-) GUID is what?

**Comment by deanlyoung** [comment]
Oops, yeah, that’s important. I believe you can use the serial number in the Apple TV’s settings: General > About > Serial Number

**Comment by Alexandre-Mainardi** [comment]
Very thanks @deanlyoung ! 

Im going to start my plugin next week

**Comment by lprhodes** [comment]
I’ve been ridiculously busy lately - I’ll be back working on it at the beginning of November.

**Comment by epheterson** [comment]
What's the method for off?

**Comment by mprajsler** [comment]
Hi exactly I also would like to know the off ;o)

**Comment by deanlyoung** [comment]
@epheterson @mprajsler I’m not aware of an off command like the wake up one I added above. Off/standby would probably require actually registering and pairing as a remote. The “wake” feature above is just sending a tcp connection, which the ATV is always listening for on standby anyway.

**Comment by postlund** [comment]
I have documented most of these things in pyatv and if you want additonal information regarding how it works, feel free to check out the documentation, e.g.:

http://pyatv.readthedocs.io/en/master/protocol.html
http://pyatv.readthedocs.io/en/master/pairing.html

Currently it only covers the DMAP/DAAP protocols, but I’m working on support for the MediRemote protocol (MRP) used by ATV4 and later as well. Some work has been committed and the stuff I’m working on is in a PR.

Regarding on/off... it will turn on if a request is sent to it, no matter how it looks like. There is no known way to turn it off, so no luck there. Maybe it’s possible with MRP but I haven’t looked at that.

**Comment by deanlyoung** [comment]
@postlund MRP should work by sending a series of commands that replicate either putting it to sleep or going into settings and powering down.

**Comment by postlund** [comment]
@deanlyoung That is of course the general idea, but a way of doing so would have to exist (what the Remote app can do is reference, the physical remote does not use MRP as that is bluetooth). I have come to the conclusion that the device has a real sleep command without having to click through menus (that would not have been a valid solution to me). This is simply accomplished by sending ``SendHIDEventMessage`` with usage page set to 0x01 and usage set to 0x82 (see https://github.com/jeanregisser/mediaremotetv-protocol/pull/3/files#diff-fab2599efff95798b9300ca6a3658972R9). It's of course not "just to do it" as MRP is quite complex. But I have lots of progress and the code I'm working on can do most basic stuff, like showing metadata, push updates and send som buttons (arrow keys, menu, etc.).

It's work-in-progress and won't be ready for use for a long time (and power-off will not be main priority, at least by me). But if someone want to try it out, its over here: https://github.com/postlund/pyatv/pull/114

**Comment by lprhodes** [comment]
Initial release is out
