### ISSUE TITLE
Is this still coming?

### ISSUE THREAD

**Issue by RickHOZ** [lprhodes/homebridge-apple-tv#4]
Any idea if this is still coming?Any alternatives/

**Comment by xlrx** [comment]
Meanwhile you can take a look at [homebridge-dacp](https://www.npmjs.com/package/homebridge-dacp).

**Comment by Kyle1519** [comment]
Bump this for the author. Any info on a possible release? Thanks!

**Comment by edc1591** [comment]
This plugin should be pretty trivial to build using [node-appletv](https://github.com/edc1591/node-appletv)

**Comment by lprhodes** [comment]
I'll be starting work on it one day this week.

**Comment by epheterson** [comment]
Apparently this is an active implementation of the dream: 
https://github.com/edc1591/homebridge-theater-mode

**Comment by Kazom** [comment]
wait so this doesn't actually work?

**Comment by lowbatteries** [comment]
First line in the description: "Note: This is just a placeholder while I work on the plugin."

**Comment by Kazom** [comment]
@lowbatteries I thought he meant placeholder of that area in the description 😂. So what the heck did I just download on my pi? install -g homebridge-apple-tv

**Comment by lowbatteries** [comment]
I have it installed on my pi too. Installed it without reading too closely. :)

**Comment by lprhodes** [comment]
Working on it currently. Let me know if there's specific use cases you want me to support

**Comment by leoneleone** [comment]
@lprhodes 
Use Cases:
1. Access to all main functions (buttons) on tv remote - including implantation for basic Right/Left/Up/Down and Enter functions.

Ideally as 1x Accessory with multiple Switches with revert back to OFF after being turned ON (momentary switches) for each Remote function. 
These can then be Grouped in the Home.app (if they appear as separate HomeKit switches) under a group named “Apple Tv Remote”. 
The user can then use these individual ‘momentary’ switches to send the Remote functions to the Apple TV. 
Example:
Apple TV Remote (Device/Accessory/Group):
- Apple TV Play (momentary switch)
- Apple TV Pause (momentary switch)
- Apple TV Menu (momentary switch) 
- Apple TV Right
- Apple TV Left
- Apple TV Enter 
- Apple TV Volume Up (momentary switch)
- Etc.

Siri Commands: 
Seeing as the switches will revert back to the OFF position. You can simply call out the name of the switch (button) and Siri will send the command to the Apple TV. 
Example: “Hey Siri, Apple TV Play”, “Hey Siri, Apple TV Menu”
there is no need to use the words ‘turns on’ to toggle the command or switch, and if the switch itself automatically revert to OFF position, then all you have to do is use the same Voice Command by calling out “Hey Siri, ‘button/switch’ name” for consecutive voice commands. 

*if ‘Apple Tv Play’ is too confusing for Siri the Name of each individual switch can be prefaced by ‘ATV’

2. A writable text (string) field which can be used in HomeKit apps like Elgato Eve for search field entries. 

3. Some way to have access to opening tv apps directly using one Switch or Command in HomeKit??

**Comment by lprhodes** [comment]
Thanks for that. It should cover all of that except potentially the Siri commands. You have to specify that a switch be turned on I thought?

**Comment by leoneleone** [comment]
@lprhodes 
No, you do not need to specify that a switch be turned On. Siri Voice Command will turn on the switch if you simple say it’s Name. I have tested this with various HomeKit switches I have. 
You do have to specify a switch be turned OFF however, but seeing as the switches will turn off automatically (to simulate a button), you will never need to use Siri Voice Comand for that 😊 

If you already have any HomeKit switches as part of your setup, please test this to confirm for yourself 👍🏼

**Comment by leoneleone** [comment]
@lprhodes 

I think this Siri Voice Command trick should mentioned in the README because it is very useful 😁

**Comment by lprhodes** [comment]
Anyone managed to get [node-appletv](https://github.com/edc1591/node-appletv) working? I'm getting "Timed out waiting for crypto sequence 2" which is preventing further development.

**Comment by lprhodes** [comment]
Thanks @edc1591 - I posted an issue. Just doing some debugging on this end.

**Comment by Kazom** [comment]
Will this support seeing the Apple TV state and triggering actions off of it. I.e. Hit the pause button, HomeKit reacts by turning on dim lights.

**Comment by edc1591** [comment]
@Kazom that is what my [homebridge-theater-mode](https://github.com/edc1591/homebridge-theater-mode) plugin does.

**Comment by Kazom** [comment]
@edc1591 awesome, I saw your project before but I thought you had to actually trigger the actions on the Apple TV 'button' yourself in the home app. Glad to know it's actually reading the states!

**Comment by jlian** [comment]
Will this support detecting if the Apple TV is asleep/standby vs on? And will this support turning on/off the Apple TV?

**Comment by lprhodes** [comment]
Yes we can detect if it’s asleep or not. Turning on just requires any command to be sent. Turning off will currently require navigating to the Sleep menu in settings but support for a proper sleep command shall be coming in a next couple of months.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by epheterson** [comment]
Couldn't you do a macro to hold the TV button, then press sleep? Might be faster than navigating to Settings.

**Comment by lprhodes** [comment]
I’m pretty much done with the plugin. Just need to write he documentation of the weekend. Unfortunately it doesn’t work with the just-released 11.3 so you may want to hold off upgrading for now.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by lprhodes** [comment]
@epheterson there’s no way to do long press currently 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by edc1591** [comment]
@lprhodes there’s a command to suspend the Apple tv

**Comment by epheterson** [comment]
I just saw a push today, is it working!? Still only pre-11.3?

**Comment by lprhodes** [comment]
Initial release is out - 11.3 issue was fixed by @edc1591 👍

**Comment by Kazom** [comment]
@lprhodes documentation is broken for config.json example: https://lprhodes.github.io/homebridge-apple-tv-slate/config-sample.json
