### ISSUE TITLE
How to Remove ‘Pair TV’ Accessories

### ISSUE THREAD

**Issue by zachgibson** [lprhodes/homebridge-apple-tv#44]
Anyone know how to get rid of the ‘Pairing’ accessories? I’ve already paired the Apple TV so this accessory is just taking up space.

![img_2215](https://user-images.githubusercontent.com/10658888/49101215-45a16f00-f23b-11e8-8d86-ccc1748d6a8e.jpg)

**Comment by ifeign** [comment]
If you read the [documentation](https://lprhodes.github.io/homebridge-apple-tv-slate/#apple-tv-discovery), it states

> You can hide "Pair" switches by adding "showPairSwitches": false to the config.

**Comment by zachgibson** [comment]
Ah, my bad. I read the docs, but I guess skipped over that part. Thanks.
