### ISSUE TITLE
Install Failed

### ISSUE THREAD

**Issue by joshbish** [lprhodes/homebridge-apple-tv#5]
pi@raspberrypi:~ $ sudo npm install -g homebridge-apple-tv
npm WARN lifecycle sodium@2.0.3~preinstall: cannot run in wd %s %s (wd=%s) sodium@2.0.3 node install.js --preinstall /usr/lib/node_modules/.staging/sodium-baf38b6a

> mdns@2.3.4 install /usr/lib/node_modules/homebridge-apple-tv/node_modules/mdns
> node-gyp rebuild

gyp WARN EACCES user "root" does not have permission to access the dev dir "/root/.node-gyp/7.10.1"
gyp WARN EACCES attempting to reinstall using temporary dev dir "/usr/lib/node_modules/homebridge-apple-tv/node_modules/mdns/.node-gyp"
make: Entering directory '/usr/lib/node_modules/homebridge-apple-tv/node_modules/mdns/build'
  CXX(target) Release/obj.target/dns_sd_bindings/src/dns_sd.o
make: g++: Command not found
dns_sd_bindings.target.mk:149: recipe for target 'Release/obj.target/dns_sd_bindings/src/dns_sd.o' failed
make: *** [Release/obj.target/dns_sd_bindings/src/dns_sd.o] Error 127
make: Leaving directory '/usr/lib/node_modules/homebridge-apple-tv/node_modules/mdns/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:194:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
gyp ERR! System Linux 4.14.30-v7+
gyp ERR! command "/usr/bin/nodejs" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /usr/lib/node_modules/homebridge-apple-tv/node_modules/mdns
gyp ERR! node -v v7.10.1
gyp ERR! node-gyp -v v3.5.0
gyp ERR! not ok 
/usr/lib
└── (empty)

npm ERR! Linux 4.14.30-v7+
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "install" "-g" "homebridge-apple-tv"
npm ERR! node v7.10.1
npm ERR! npm  v4.2.0
npm ERR! code ELIFECYCLE
npm ERR! errno 1

npm ERR! mdns@2.3.4 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the mdns@2.3.4 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the mdns package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs mdns
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls mdns
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /root/.npm/_logs/2018-04-03T03_12_07_273Z-debug.log
pi@raspberrypi:~ $ node -v
v7.10.1

**Comment by MrDrache333** [comment]
Try sudo npm install -g homebridge-apple-tv --unsafe-perm

**Comment by joshbish** [comment]
pi@raspberrypi:~ $ sudo npm install -g homebridge-apple-tv --safe-perm
npm WARN lifecycle sodium@2.0.3~preinstall: cannot run in wd %s %s (wd=%s) sodium@2.0.3 node install.js --preinstall /usr/lib/node_modules/.staging/sodium-baf38b6a

> mdns@2.3.4 install /usr/lib/node_modules/homebridge-apple-tv/node_modules/mdns
> node-gyp rebuild

gyp WARN EACCES user "root" does not have permission to access the dev dir "/root/.node-gyp/7.10.1"
gyp WARN EACCES attempting to reinstall using temporary dev dir "/usr/lib/node_modules/homebridge-apple-tv/node_modules/mdns/.node-gyp"
make: Entering directory '/usr/lib/node_modules/homebridge-apple-tv/node_modules/mdns/build'
  CXX(target) Release/obj.target/dns_sd_bindings/src/dns_sd.o
make: g++: Command not found
dns_sd_bindings.target.mk:149: recipe for target 'Release/obj.target/dns_sd_bindings/src/dns_sd.o' failed
make: *** [Release/obj.target/dns_sd_bindings/src/dns_sd.o] Error 127
make: Leaving directory '/usr/lib/node_modules/homebridge-apple-tv/node_modules/mdns/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:194:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
gyp ERR! System Linux 4.14.30-v7+
gyp ERR! command "/usr/bin/nodejs" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /usr/lib/node_modules/homebridge-apple-tv/node_modules/mdns
gyp ERR! node -v v7.10.1
gyp ERR! node-gyp -v v3.5.0
gyp ERR! not ok 
/usr/lib
└── (empty)

npm ERR! Linux 4.14.30-v7+
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "install" "-g" "homebridge-apple-tv" "--safe-perm"
npm ERR! node v7.10.1
npm ERR! npm  v4.2.0
npm ERR! code ELIFECYCLE
npm ERR! errno 1

npm ERR! mdns@2.3.4 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the mdns@2.3.4 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the mdns package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs mdns
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls mdns
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /root/.npm/_logs/2018-04-03T03_33_31_647Z-debug.log

**Comment by MrDrache333** [comment]
Hatte den selben fehler mit Soduim bei einem anderen Plugin...dort hat es bestens funktioniert...ich muss jetzt zur Arbeit...wenn sich bis heut nachmittag keiner Meldet probier ich nochmal und poste dir eine evtl. Lösung ;)

**Comment by joshbish** [comment]
Thanks!

**Comment by glassbase** [comment]
I am also getting the sodium error on install

Edit - I think my issue is related to needed node v9 for node-appletv. The docker I use doesn’t have node v9

**Comment by MrDrache333** [comment]
Ok...installation works...use the Command 'sudo npm install -g homebridge-apple-tv --unsafe-perm' and make sure you updated your Pi before with 'apt-get update -y && apt-get upgrade -y && npm i -g npm'. During 'sudo npm install -g homebridge-apple-tv --unsafe-perm' you will get tons of Compiling output...like 10-15min.....but it works XD

Else post your Error code ;)

EDIT: My installation took exact 646.05s ;)

**Comment by crazy-jackrabbit** [comment]
Also getting the Sodium error...

Node Version: 7.10.0
Command: "sudo npm install -g homebridge-apple-tv --safe-perm"
Error:

> 
> sodium@2.0.3 preinstall /usr/local/lib/node_modules/homebridge-apple-tv/node_modules/sodium
> node install.js --preinstall
> Static libsodium was not found at /usr/local/lib/node_modules/homebridge-apple-tv/node_modules/sodium/deps/build/lib/libsodium so compiling libsodium from source.
> libtool is required, but wasn't found on this system
> Makefile:61: recipe for target 'libsodium' failed
> make: *** [libsodium] Error 1
> /usr/local/lib/node_modules/homebridge-apple-tv/node_modules/sodium/install.js:287
>             throw new Error(cmdLine + ' exited with code ' + code);
>             ^
> 
> Error: make libsodium exited with code 2
>     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/homebridge-apple-tv/node_modules/sodium/install.js:287:19)
>     at emitTwo (events.js:106:13)
>     at ChildProcess.emit (events.js:194:7)
>     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
> npm ERR! code ELIFECYCLE
> npm ERR! errno 1
> npm ERR! sodium@2.0.3 preinstall: `node install.js --preinstall`
> npm ERR! Exit status 1
> npm ERR! 
> npm ERR! Failed at the sodium@2.0.3 preinstall script.
> npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
> 
> npm ERR! A complete log of this run can be found in:
> npm ERR!     /root/.npm/_logs/2018-04-03T15_28_04_992Z-debug.log

**Comment by MrDrache333** [comment]
'sudo npm install -g homebridge-apple-tv --unsafe-perm'  not --safe-perm...my fault :)

**Comment by crazy-jackrabbit** [comment]
thx
new try, new error:

> sudo npm install -g homebridge-apple-tv --unsafe-perm
> 
> > sodium@2.0.3 preinstall /usr/local/lib/node_modules/homebridge-apple-tv/node_modules/sodium
> > node install.js --preinstall
> 
> Static libsodium was not found at /usr/local/lib/node_modules/homebridge-apple-tv/node_modules/sodium/deps/build/lib/libsodium so compiling libsodium from source.
> libtool is required, but wasn't found on this system
> Makefile:61: recipe for target 'libsodium' failed
> make: *** [libsodium] Error 1
> /usr/local/lib/node_modules/homebridge-apple-tv/node_modules/sodium/install.js:287
>             throw new Error(cmdLine + ' exited with code ' + code);
>             ^
> 
> Error: make libsodium exited with code 2
>     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/homebridge-apple-tv/node_modules/sodium/install.js:287:19)
>     at emitTwo (events.js:106:13)
>     at ChildProcess.emit (events.js:194:7)
>     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
> npm ERR! code ELIFECYCLE
> npm ERR! errno 1
> npm ERR! sodium@2.0.3 preinstall: `node install.js --preinstall`
> npm ERR! Exit status 1
> npm ERR! 
> npm ERR! Failed at the sodium@2.0.3 preinstall script.
> npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
> 
> npm ERR! A complete log of this run can be found in:
> npm ERR!     /root/.npm/_logs/2018-04-03T15_52_58_818Z-debug.log

**Comment by MrDrache333** [comment]
It says "libtool is required, but wasn't found on this system" try solve this by install it ;) 'apt-get install libtool' I think it also requires to install 'autoconf'...try to install that also manually by typing 'apt-get install autoconf'...hope this helps :)

**Comment by DJay-X** [comment]
Same here with the install error. 
I try @MrDrache333 's tips tomorrow. Thx for this.
But would be great to see detailed installation instructions from @lprhodes 
Wondering that there isn't a word about sodium etc. and other things that you have to have install in addition to the plugin. Bit confusing. 🤷🏼‍♂️

```
~ $ sudo npm install -g homebridge-apple-tv --unsafe-perm

> sodium@2.0.3 preinstall /usr/local/lib/node_modules/homebridge-apple-tv/node_modules/sodium
> node install.js --preinstall

Static libsodium was not found at /usr/local/lib/node_modules/homebridge-apple-tv/node_modules/sodium/deps/build/lib/libsodium so compiling libsodium from source.
libtool is required, but wasn't found on this system
Makefile:61: die Regel für Ziel „libsodium“ scheiterte
make: *** [libsodium] Fehler 1
/usr/local/lib/node_modules/homebridge-apple-tv/node_modules/sodium/install.js:287
            throw new Error(cmdLine + ' exited with code ' + code);
            ^

Error: make libsodium exited with code 2
    at ChildProcess.<anonymous> (/usr/local/lib/node_modules/homebridge-apple-tv/node_modules/sodium/install.js:287:19)
    at ChildProcess.emit (events.js:180:13)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:209:12)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! sodium@2.0.3 preinstall: `node install.js --preinstall`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the sodium@2.0.3 preinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```

**Comment by jat80** [comment]
Similar problem here but using macOS Sierra 10.12.6

Mac-Mini:~ user$ sudo npm install -g homebridge-apple-tv --unsafe-perm

> sodium@2.0.3 preinstall /usr/local/lib/node_modules/homebridge-apple-tv/node_modules/sodium
> node install.js --preinstall

Static libsodium was not found at /usr/local/lib/node_modules/homebridge-apple-tv/node_modules/sodium/deps/build/lib/libsodium so compiling libsodium from source.
libtool is required, but wasn't found on this system
make: *** [libsodium] Error 1
/usr/local/lib/node_modules/homebridge-apple-tv/node_modules/sodium/install.js:287
            throw new Error(cmdLine + ' exited with code ' + code);
            ^

Error: make libsodium exited with code 2
    at ChildProcess.<anonymous> (/usr/local/lib/node_modules/homebridge-apple-tv/node_modules/sodium/install.js:287:19)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! sodium@2.0.3 preinstall: `node install.js --preinstall`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the sodium@2.0.3 preinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/user/.npm/_logs/2018-04-04T02_50_13_512Z-debug.log

Any thoughts @lprhodes ?

**Comment by MrDrache333** [comment]
Also after the installation of libtool and autoconf? I installed previusly node-appletv. This plugin also needed sodium...i fixed that by installing the other needet packages manually...like i sayed

@jat80 & @DJay-X

**Comment by DJay-X** [comment]
Separate install with `sudo apt-get install libtool` and  `sudo apt-get install autoconf` worked for me. Thx @MrDrache333

**Comment by jat80** [comment]
what would be the command for macOS / homebrew?

don't worry - found it!  

It's ` brew install libtool `and `brew install autoconf`

You will need homebrew obviously (Mac users)

**Comment by jat80** [comment]
still getting errors:

Mac-Mini:~ user$  sudo npm install -g homebridge-apple-tv --unsafe-perm

> sodium@2.0.3 preinstall /usr/local/lib/node_modules/homebridge-apple-tv/node_modules/sodium
> node install.js --preinstall

Static libsodium was not found at /usr/local/lib/node_modules/homebridge-apple-tv/node_modules/sodium/deps/build/lib/libsodium so compiling libsodium from source.
automake is required, but wasn't found on this system
make: *** [libsodium] Error 1
/usr/local/lib/node_modules/homebridge-apple-tv/node_modules/sodium/install.js:287
            throw new Error(cmdLine + ' exited with code ' + code);
            ^

Error: make libsodium exited with code 2
    at ChildProcess.<anonymous> (/usr/local/lib/node_modules/homebridge-apple-tv/node_modules/sodium/install.js:287:19)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! sodium@2.0.3 preinstall: `node install.js --preinstall`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the sodium@2.0.3 preinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/user/.npm/_logs/2018-04-04T23_32_59_755Z-debug.log

Any ideas?  I also tried brew install libsodium which installed but still not luck.

**Comment by MrDrache333** [comment]
`automake is required, but wasn't found on this system `

Try install it too with `apt-get install automake` or `brew install automake`

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by jat80** [comment]
Thanks @MrDrache333 It's all installed now! :)

**Comment by joshbish** [comment]
I got much farther along after installing lib tool and autoconf and then running sudo npm install -g homebridge-apple-tv --unsafe-perm.  Now I am getting this ...

make: Entering directory '/usr/lib/node_modules/homebridge-apple-tv/node_modules/mdns/build'
  CXX(target) Release/obj.target/dns_sd_bindings/src/dns_sd.o
make: g++: Command not found
dns_sd_bindings.target.mk:149: recipe for target 'Release/obj.target/dns_sd_bindings/src/dns_sd.o' failed
make: *** [Release/obj.target/dns_sd_bindings/src/dns_sd.o] Error 127
make: Leaving directory '/usr/lib/node_modules/homebridge-apple-tv/node_modules/mdns/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:194:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
gyp ERR! System Linux 4.14.30-v7+
gyp ERR! command "/usr/bin/nodejs" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /usr/lib/node_modules/homebridge-apple-tv/node_modules/mdns
gyp ERR! node -v v7.10.1
gyp ERR! node-gyp -v v3.5.0
gyp ERR! not ok 
/usr/lib
└── (empty)

npm ERR! Linux 4.14.30-v7+
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "install" "-g" "homebridge-apple-tv" "--unsafe-perm"
npm ERR! node v7.10.1
npm ERR! npm  v4.2.0
npm ERR! code ELIFECYCLE
npm ERR! errno 1

npm ERR! mdns@2.3.4 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the mdns@2.3.4 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the mdns package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs mdns
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls mdns
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /root/.npm/_logs/2018-04-06T16_46_25_556Z-debug.log

**Comment by MrDrache333** [comment]
Try to install g++ with `sudo apt-get install g++ ` cause it Looks like its not installed -> `make: g++: Command not found`

**Comment by joshbish** [comment]
That worked, thanks!

**Comment by thejoaovitor** [comment]
sudo apt-get install autoconf automake g++ libtool

autoconf is already the newest version (2.69-10).
automake is already the newest version (1:1.15-6).
g++ is already the newest version (4:6.3.0-4).
libtool is already the newest version (2.4.6-2).

Now I'm getting this errors in Raspibian

> sodium@2.0.3 preinstall /usr/lib/node_modules/homebridge-apple-tv/node_modules/sodium
> node install.js --preinstall

Static libsodium was not found at /usr/lib/node_modules/homebridge-apple-tv/node_modules/sodium/deps/build/lib/libsodium so compiling libsodium from source.
libtoolize:   error: Failed to create 'build-aux'
make: *** [libsodium] Error 1
Makefile:61: recipe for target 'libsodium' failed
/usr/lib/node_modules/homebridge-apple-tv/node_modules/sodium/install.js:287
            throw new Error(cmdLine + ' exited with code ' + code);
            ^

Error: make libsodium exited with code 2
    at ChildProcess.<anonymous> (/usr/lib/node_modules/homebridge-apple-tv/node_modules/sodium/install.js:287:19)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! sodium@2.0.3 preinstall: `node install.js --preinstall`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the sodium@2.0.3 preinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2018-08-03T01_46_46_211Z-debug.log

@MrDrache333 could you please help me

**Comment by MrDrache333** [comment]
Can you try to install the whole Plugin again with `sudo npm install -g homebridge-apple-tv --unsafe-perm`?

**Comment by MsCopernic** [comment]
@MrDrache333 after installing automake, sudo npm install -g homebridge-apple-tv --unsafe-perm works perfectly.Thanks !!

**Comment by sushenmathur** [comment]
Having issue installing.. 

autoconf is already the newest version (2.69-10).
automake is already the newest version (1:1.15-6).
g++ is already the newest version (4:6.3.0-4).
libtool is already the newest version (2.4.6-2).

all are installed correctly. 

Error Log: 

> > sodium@2.0.3 preinstall /usr/local/lib/node_modules/homebridge-apple-tv/node_modules/sodium
> node install.js --preinstall

Static libsodium was not found at /usr/local/lib/node_modules/homebridge-apple-tv/node_modules/sodium/deps/build/lib/libsodium so compiling libsodium from source.
libtool is required, but wasn't found on this system
make: *** [Makefile:62: libsodium] Error 1
/usr/local/lib/node_modules/homebridge-apple-tv/node_modules/sodium/install.js:287
            throw new Error(cmdLine + ' exited with code ' + code);
            ^

Error: make libsodium exited with code 2
    at ChildProcess.<anonymous> (/usr/local/lib/node_modules/homebridge-apple-tv/node_modules/sodium/install.js:287:19)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! sodium@2.0.3 preinstall: `node install.js --preinstall`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the sodium@2.0.3 preinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2018-10-05T02_21_18_871Z-debug.log


Please help

**Comment by MsCopernic** [comment]
Hi @sushenmathur, try installing libsodium with the following command:

sudo npm install -g libsodium

This works for MAC and PI

**Comment by sushenmathur** [comment]
@MsCopernic 
tried installing as your suggested still getting the same error

```
/homebridge # npm install -g libsodium
+ libsodium@0.7.3
updated 1 package in 3.691s
/homebridge #  npm --no-update-notifier install --unsafe-perm --save homebridge-apple-tv@latest

> sodium@2.0.3 preinstall /homebridge/node_modules/sodium
> node install.js --preinstall

Static libsodium was not found at /homebridge/node_modules/sodium/deps/build/lib/libsodium so compiling libsodium from source.
libtool is required, but wasn't found on this system
make: *** [Makefile:62: libsodium] Error 1
/homebridge/node_modules/sodium/install.js:287
            throw new Error(cmdLine + ' exited with code ' + code);
            ^

Error: make libsodium exited with code 2
    at ChildProcess.<anonymous> (/homebridge/node_modules/sodium/install.js:287:19)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
npm WARN homebridge No description
npm WARN homebridge No repository field.
npm WARN homebridge No license field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! sodium@2.0.3 preinstall: `node install.js --preinstall`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the sodium@2.0.3 preinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2018-10-09T05_27_48_031Z-debug.log 
```

**Comment by jblakeney82** [comment]
@MsCopernic 

Did you ever get your Apple TV libsodium and lib tools errors resolved? I am having the same issue and have installed and read every support doc I can find with no luck.

**Comment by MsCopernic** [comment]
Hi @jblakeney82, I did, but I can't tell you how, because I made no notes of the process. I'm making a clean installation and taking notes, as soon as I have something, I will contact you. Looks that there is no standard procedure to make this work uh?

**Comment by jblakeney82** [comment]
It’s been a super pain, it’s not libtools or perhaps where libtools is installed is not where it is supposed to be or the install is looking in the wrong place...?

**Comment by jblakeney82** [comment]
Hey were you ever able to rebuild and get theater mode running? 

I am now going to start fresh and try another os build for my PI or try using docker on my synology NAS.

**Comment by MsCopernic** [comment]
Hi @jblakeney82; just curious, did you installed Xcode development tools from Xcode or did you installed only the Xcode development tools?

**Comment by jblakeney82** [comment]
Neither, this is running On my raspberry pi

**Comment by theodorjs** [comment]
After manually installing lib tool, automake and autoconf it looked like it would work, but after a long installation process I got the following error. Running on a Mac mini with Mojave. I've added the full log file from the installation process. I tried installing using "npm install -g homebridge-apple-tv --unsafe-perm"
[Terminal Saved Output.txt](https://github.com/lprhodes/homebridge-apple-tv/files/2615136/Terminal.Saved.Output.txt)

Error: make nodesodium exited with code null
    at ChildProcess.<anonymous> (/usr/local/lib/node_modules/homebridge-apple-tv/node_modules/sodium/install.js:287:19)
    at ChildProcess.emit (events.js:182:13)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:246:12)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! sodium@2.0.3 install: `node install.js --install`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the sodium@2.0.3 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
Mac-mini:~ theodorsandaker$

**Comment by theodorjs** [comment]
After manually installing libtool, autoconf and libsodium _(on my Mac mini running Mojave)_ it looked like it would work. The installer ran for a long time after using "sudo npm install -g homebridge-apple-tv --unsafe-perm", but it returned with the following error message:

Error: make nodesodium exited with code null
    at ChildProcess.<anonymous> (/usr/local/lib/node_modules/homebridge-apple-tv/node_modules/sodium/install.js:287:19)
    at ChildProcess.emit (events.js:182:13)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:246:12)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! sodium@2.0.3 install: `node install.js --install`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the sodium@2.0.3 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/theodorsandaker/.npm/_logs/2018-11-26T11_17_24_340Z-debug.log

I've attached the [Complete log](https://github.com/lprhodes/homebridge-apple-tv/files/2615234/2018-11-26T11_17_24_340Z-debug.log)

**Comment by petikist** [comment]
Hey, same here. I've check everything I can, but keep getting the exact same problems as you @theodorjs 

Did you find something ?

**Comment by theodorjs** [comment]
Sadly not, @petikist 
I've given up for now.

**Comment by Pensive** [comment]
I'm getting the same problem now; Previously fully working :(

My nas rebooted and the docker runs updates when it boots. 
`apt-get update
apt-get install -y libtool
apt-get install -y autoconf`

Then i got a node version error when the apple tv plugins tried to load - i've lost the log quote now :-/

So i ran a bunch of updates, uninstalled, reinstalled etc. but they dump out as below

`
Error: make nodesodium exited with code null
    at ChildProcess.<anonymous> (/usr/local/lib/node_modules/homebridge-apple-tv/node_modules/sodium/install.js:287:19)
    at ChildProcess.emit (events.js:182:13)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:240:12)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! sodium@2.0.3 install: `node install.js --install`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the sodium@2.0.3 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2018-11-29T23_26_37_199Z-debug.log`

And now all i get is:
`[11/29/2018, 11:38:18 PM] Loaded config.json with 1 accessories and 2 platforms.
[11/29/2018, 11:38:18 PM] ---
[11/29/2018, 11:38:18 PM] Plugin /homebridge/node_modules/homebridge-platform-helper package.json does not contain the keyword 'homebridge-plugin'.`

Just going to remove it from the config for now- been at it two hours with no joy.

**Comment by jhc247** [comment]
I was able to install the plugin on my Raspberry Pi 3 using these steps:
1: sudo apt-get install libtool
2: sudo apt-get install autoconf
3: sudo npm install -g homebridge-apple-tv

**Comment by Pensive** [comment]
Yeah - I originally got it all working but every time my NAS reboots or docker updates the docker restarts and the update runs. I’m going to pull it all out into raspi instead with no auto updates.....

That or buy a Crestron cp3 processor

**Comment by jblakeney82** [comment]
still no dice for me, I have tried installing those tools and using that process before, even wiping my pi and starting fresh with same result unfortunately. 

> sodium@2.0.3 preinstall /usr/local/lib/node_modules/homebridge-apple-tv/node_modules/sodium
> node install.js --preinstall

Static libsodium was not found at /usr/local/lib/node_modules/homebridge-apple-tv/node_modules/sodium/deps/build/lib/libsodium so compiling libsodium from source.
libtoolize:   error: Failed to create 'build-aux'
make: *** [libsodium] Error 1
Makefile:61: recipe for target 'libsodium' failed
/usr/local/lib/node_modules/homebridge-apple-tv/node_modules/sodium/install.js:287
            throw new Error(cmdLine + ' exited with code ' + code);
            ^

Error: make libsodium exited with code 2
    at ChildProcess.<anonymous> (/usr/local/lib/node_modules/homebridge-apple-tv/node_modules/sodium/install.js:287:19)
    at ChildProcess.emit (events.js:182:13)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:254:12)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! sodium@2.0.3 preinstall: `node install.js --preinstall`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the sodium@2.0.3 preinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2018-12-02T14_52_29_506Z-debug.log
