### ISSUE TITLE
Plugin Breaks with Homebridge V1.0.0-1.0.1

### ISSUE THREAD

**Issue by NajibNour** [lprhodes/homebridge-apple-tv#56]
Plugin Breaks with Homebridge V1.0.0-1.0.1
The homebridge-apple-tv plugin only works with node version 8, and the new homebridge requires node version v10.17.0.
So after updating, I realized homebridge-apple-tv was uninstalled when trying to reinstall I ran into multiple errors.

[errors.txt](https://github.com/lprhodes/homebridge-apple-tv/files/4540371/errors.txt)

beware when updating your node version as it will break this plugin.

Looking forward to a fix as this was one of my favorite plugins.

**Comment by NorthernMan54** [comment]
As a work around I installed homebridge-Apple-tv-remote instead and it has been great

**Comment by NajibNour** [comment]
@NorthernMan54 I will give it a shot! Thanks for the help!
