### ISSUE TITLE
Conflict with homebridge-config-ui-x

### ISSUE THREAD

**Issue by normen** [lprhodes/homebridge-apple-tv#9]
It seems that the config-example.json is missing entries in the "devices" section. With the default example the plugin complains that theres no device called "lounge". I added a simple section like

```
{
   "deviceID": "lounge"
}
```

but I am getting this error when booting up after that:

```
(node:27838) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 2): TypeError: Cannot read property 'split' of undefined
(node:27838) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

Am I missing something else in that devices entry?

**Comment by normen** [comment]
Ah, the web site is a bit messed up on safari, I didn't notice the section about the first boot.. Anyway if i remove it I get this error, thats why I thought it was incomplete in the first place.

```
[Apple TV] [CONFIG ERROR] Up; No connected device could be found with a deviceID of "lounge".
```

**Comment by normen** [comment]
... and looking further I guess that is because the AppleTV can't be found in the first place... So I suppose thats the core issue here..

Funny because the AppleTV is the HomeKit hub and definitely can connect to the RasPi running HomeBridge...

**Comment by epheterson** [comment]
The instructions are kind of misleading, especially with references to "lounge" which is the author's Apple TV.

You're supposed to start out with nothing in the devices[] section, and as such, any references to specific devices will throw warnings/errors.

You should see a toggle in the Home App for your Apple TV. Turning that on should put a code on the Apple TV. The Homebridge CLI will then ask you to type the code and hit enter. The CLI will then give you auth credentials to paste into the devices[] section. You can optionally name your device "lounge" to correspond with the examples in config-sample.json.

Hope this helps!

**Comment by DJay-X** [comment]
Thanks @epheterson 
I check the log of Homebridge on my Pi with `sudo journalctl -f -u homebridge`. But I have no clue where or how to type in the code from Apple TV? The log is just a log that don't accept input. Sorry for maybe asking such a stupid question. And thanks in advance for the help.

**Comment by epheterson** [comment]
I’m not really sure, I think providing input in this way is kinda weird for precisely that reason. Maybe there should be some other method, like a tool in the node folder you can run for setup. I had to do this for my homebridge-switchmate setup and after using the tool was able to configure the plugin with no input needed.

**Comment by epheterson** [comment]
You also should be able to run homebridge directly, but not sure how to provide steps for your setup. You’d only need to run it manually once, then could go back to any other method. 

For example, on my Mac it runs on boot with launchctl, but when modifying things I stop the process and run the same command manually in terminal to watch the output and debug quickly.

**Comment by DJay-X** [comment]
Got it... Just stop the Homebridge on Pi

- `sudo systemctl stop homebridge`
- then just run `homebridge`
- Press the pair button in Home App
- In the Terminal there you now can enter the code.
- After this ctrl+c
- Edit the config.json with the snipped
- restart homebridge `sudo systemctl start homebridge`

thanks @epheterson for pointing to the right direction. 👍🏻

**Comment by normen** [comment]
Nah, it actually doesn't find my Apple TV, still investigating why thats the case. So with a correct, config.json theres no pair toggle, and no log output out of the ordinary either. The plugin starts up, says it scans for Apple TVs but none appear.

As said the Apple TV is the HomeKit central so they do have network connection.. It's an Apple TV of the previous generation (without the white circle around the mic button on the remote).

Sorry for the confusion, this behavior made me think I'd have to add something else to the config file.

**Comment by normen** [comment]
Looks like it works when I run as a different user, I am running on a raspberry pi and with a separate user called "homebridge", when I run the homebridge process as "pi" it works (i.e. finds the ATV)..

**Comment by normen** [comment]
Not the user, it simply doesn't work in my main setup / config. When I start with an "empty" Homebridge it works - but I don't have that one registered in my HomeKit setup so I can't toggle the pair switch to get a credentials file -.-

**Comment by MrDrache333** [comment]
Can you pair and get the credentials by using the command `appletv pair`?

**Comment by normen** [comment]
Huh? Where would that command be? Do I have to install one of the dependency packages globally for that? Edit: found it, that seems to work.. Now for looking if it works in homebridge.

**Comment by MrDrache333** [comment]
Its `node appletv` but I think this home bridge plugin use that as well..I can't check that because I use this node plugin also with homebridge 😃 You might be able to install it via `nom install -g node-appletv`

**Comment by normen** [comment]
Yeah. I can get a credentials line from the command line but then when I run it in my actual homebridge setup (same user) it doesn't find the Apple TV... Seems like some other plugin is interfering or something? As said when I run homebridge with only the AppleTV plugin it works o_O

**Comment by MrDrache333** [comment]
Thats why i created some kind of Buttons on my own with this plugins...it uses the `homebridge-cmdswitch2` Plugin witch are configured to run those commands stored in a shell File 

Pause.sh:
`Appletv command pause --credentials ........`

Homebridge-config:
`{
          "off_cmd" : "",
          "interval" : 5,
          "state_cmd" : "echo 0 | grep -c 1",
          "name" : "Start",
          "on_cmd" : "./appletv/keno/play.sh",
          "polling" : true
        },
        {
          "off_cmd" : "",
          "interval" : 5,
          "state_cmd" : "echo 0 | grep -c 1",
          "name" : "Stop",
          "on_cmd" : "./appletv/keno/pause.sh",
          "polling" : true
        } `

The Polling and none Off cmd are just a kind of an automatic off Switch Simulation and work still very well...the sate is kind of Stupid but simple 😃 just gett the count of ones out of a null...witch is null e.g. False...so the Button will go to its Off state

**Comment by normen** [comment]
Right, thats an option. I don‘t need the AppleTV in there that badly though.. Really only for the „turn on the fireplace“ scene ;) If it was working through this plugin that‘d be much more convenient, especially when its actually about pressing different keys etc, that command line would quickly grow out of proportion.

**Comment by normen** [comment]
I seem to have found the offending plugin that prevents this plugin from working, if I disable this plugin then the AppleTV can be found:

https://github.com/oznu/homebridge-config-ui-x

I'll report this to the developer as well.

**Comment by normen** [comment]
Okaaayy.. So it looks like the issue is simply that during the startup of the homebridge server there is so much going on that the AppleTV plugin doesn't get a cycle to receive the AppleTV discovery message.

The config-ui-x developer was very helpful and he - probably correctly - suggests that the AppleTV plug should probably have a retry function when the AppleTV signal wasn't received after a while.

**Comment by DarKOrange75** [comment]
So why is this ticket closed? The issue is not fixed and I can't use the Apple TV plugin because I also run the config-ui-x plugin. Please add a retry function to the Apple TV discovery at startup. Thank you.
